# Default values for matts jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
metadata:
  appname: dieroll
  namespace: unleashdemo


release: v1
image: 
  repo: housems/unleashdie
  tag: v1
  pullpolicy: Always
#imagePullSecrets: regcred
nodeSelector:
  arch: arm
#  hostname: anton
replicas: 1
internalport: 3000
externalport: 80
host: dieroll.antontheserver.net
