apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.appname }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  ports:
    - port: {{ .Values.externalport }}
      targetPort: {{ .Values.internalport }}
      protocol: TCP
  type: NodePort
  selector:
    app: {{ .Values.metadata.appname }}
    release: {{ .Values.release }}