# Default values for matts jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
metadata:
  appname: nextcloud
  namespace: nextcloud


release: v1
image: 
  repo: unleashorg/unleash-server
  tag: latest
  pullpolicy: Always
#imagePullSecrets: regcred
nodeSelector:
  arch: amd64
#  hostname: anton
replicas: 1
internalport: 80
externalport: 80
host: unleash.antontheserver.net
env:
  name1: DATABASE_HOST
  value1: x
  name2: DATABASE_NAME
  value2: unleash
  name3: DATABASE_USERNAME
  value3: unleash
  name4: DATABASE_PASSWORD
  value4: unleash

volumes:
  volume1:
    name: ncdata
    mountPath: /var/www/html/
    hostPath: /mnt/nfs_clientshare/nextcloud/ncserver
    type: DirectoryOrCreate
